AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.7.0
  Exclude:
    - '**/*.yml'
    - 'db/**/*'
    - 'config/**/*'
    - 'doc/**/*'
    - 'deployment/**/*'
    - 'bin/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/wulin_app/db/**/*'
    - 'lib/generators/wulin_master/screen_and_grid/templates/*.rb'
    - 'lib/wulin_master/authorization.rb'

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/LineLength:
  Max: 165

Layout/DotPosition:
  EnforcedStyle: trailing

Style/FormatString:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Metrics/MethodLength:
  Max: 40

Layout/CaseIndentation:
  # Valid values are: case, end
  EnforcedStyle: end
  IndentOneStep: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/ParameterLists:
  Max: 10

Lint/UselessAssignment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'spec/wulin_app/bin/*'

Metrics/BlockLength:
  Max: 35
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/ModuleLength:
  Max: 250

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 25

Lint/SuppressedException:
  Exclude:
    - 'app/screens/grid_states_screen.rb'
    - 'lib/wulin_master/components/grid/column/column_filter.rb'

Style/ClassVars:
  Exclude:
    - 'lib/wulin_master/components/grid/grid_actions.rb'

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
