# -*- encoding: utf-8 -*-
WulinMaster.configure do |config|
  # The title of the page, default value is "Terra Nova"
  # config.app_title = "Terra Nova"
  
  # The name of the folder which generated by <b>wulin_master:screen_and_grid</b> generator,defalut value is 'terra_nova'
  # config.asset_folder_name = 'terra_nova'
  
  # The split pattern of the array params, default is /,|，/
  # config.param_value_split_pattern = /,|，/
end