WulinMaster.configure do |config|
  # The title of the page
  config.app_title = "Terra Nova"
  
  # The name of the folder which generated by <b>wulin_master:screen_and_grid</b> generator
  config.asset_folder_name = 'terra_nova'
end