# -*- encoding: utf-8 -*-
WulinMaster.configure do |config|
  # The title of the page, default value is "Undefined App"
  # config.app_title = "Undefined App"
  
  # The name of the folder which generated by <b>wulin_master:screen_and_grid</b> generator,defalut value is 'wulin_master'
  # config.asset_folder_name = 'wulin_master'
end